app:
  tsudb:
    enabled: true
    remote-type: timetable
    import-source: network
    path: path-to-server
    cache-path: path-to-dir
    current-season: 2019 - 2020
    semester: Осень
    cron: "-"
  week-sign:
    primary-info:
      facultyName: Факультет прикладной математики и кибернетики
      date: 2023-09-04
      week-sign: MINUS
      week-sign-strategy: plusminus
spring:
  jmx:
    default-domain: com.a6raywa1cher.rescheduletsuspring
    unique-names: true
# ===============================
# DB CONNECTION
# ===============================
spring.datasource.url: jdbc:postgresql://localhost:5432/reschedule-tsu
spring.datasource.username: postgres
spring.datasource.password: Ofss57ArFFNAZfNL9cWO
# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.show-sql: false
spring.jpa.hibernate.ddl-auto: update
spring.jpa.properties.hibernate:
  default_schema: public
  current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
  use_jdbc_metadata_defaults: false
# ===============================
# SPRING ACTUATOR
# ===============================
#management.endpoints.web.exposure.include: "*"