app:
  tsudb:
    import-source: network
    path: path-to-server
    cache-path: path-to-dir
    current-season: 2019 - 2020
    cron: "-"
  admin-token: eqnfoiwehojJSQ
  week-sign:
    primary-info:
      facultyName: ПМиК
      date: 2019-09-07
      weekSign: MINUS
      weekSignStrategy: plusminus
# ===============================
# DB CONNECTION
# ===============================
spring.datasource.url: jdbc:postgresql://localhost:5433/reschedule-tsu
spring.datasource.username: postgres
spring.datasource.password: postgres
# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.show-sql: true
spring.jpa.hibernate.ddl-auto: update
spring.jpa.properties.hibernate.default_schema: public
spring.jpa.properties.hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: false
# ===============================
# SPRING ACTUATOR
# ===============================
#management.endpoints.web.exposure.include: "*"